FROM apache/airflow:2.10.3

# Немного системных пакетов (на всякий случай для сборки)
USER root
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*
USER airflow

# Всё, что нужно внутри Airflow-контейнера
RUN pip install --no-cache-dir \
    feast==0.46.0 \
    pandas \
    pyarrow \
    scikit-learn \
    joblib

